/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ApiReviewsGetCollection200,
  ApiReviewsGetCollectionParams,
  ConstraintViolationJson,
  ConstraintViolationJsonldJsonld,
  Error,
  ErrorJsonld,
  Review,
  ReviewJsonld,
} from ".././models";

import { customFetch } from ".././custom-fetch";

// https://stackoverflow.com/questions/49579094/typescript-conditional-types-filter-out-readonly-properties-pick-only-requir/49579497#49579497
type IfEquals<X, Y, A = X, B = never> =
  (<T>() => T extends X ? 1 : 2) extends <T>() => T extends Y ? 1 : 2 ? A : B;

type WritableKeys<T> = {
  [P in keyof T]-?: IfEquals<
    { [Q in P]: T[P] },
    { -readonly [Q in P]: T[P] },
    P
  >;
}[keyof T];

type UnionToIntersection<U> = (U extends any ? (k: U) => void : never) extends (
  k: infer I,
) => void
  ? I
  : never;
type DistributeReadOnlyOverUnions<T> = T extends any ? NonReadonly<T> : never;

type Writable<T> = Pick<T, WritableKeys<T>>;
type NonReadonly<T> = [T] extends [UnionToIntersection<T>]
  ? {
      [P in keyof Writable<T>]: T[P] extends object
        ? NonReadonly<NonNullable<T[P]>>
        : T[P];
    }
  : DistributeReadOnlyOverUnions<T>;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Retrieves the collection of Review resources.
 * @summary Retrieves the collection of Review resources.
 */
export type apiReviewsGetCollectionResponse200 = {
  data: ApiReviewsGetCollection200;
  status: 200;
};

export type apiReviewsGetCollectionResponseSuccess =
  apiReviewsGetCollectionResponse200 & {
    headers: Headers;
  };
export type apiReviewsGetCollectionResponse =
  apiReviewsGetCollectionResponseSuccess;

export const getApiReviewsGetCollectionUrl = (
  params?: ApiReviewsGetCollectionParams,
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `http://localhost:3000/reviews?${stringifiedParams}`
    : `http://localhost:3000/reviews`;
};

export const apiReviewsGetCollection = async (
  params?: ApiReviewsGetCollectionParams,
  options?: RequestInit,
): Promise<apiReviewsGetCollectionResponse> => {
  return customFetch<apiReviewsGetCollectionResponse>(
    getApiReviewsGetCollectionUrl(params),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getApiReviewsGetCollectionQueryKey = (
  params?: ApiReviewsGetCollectionParams,
) => {
  return [
    `http://localhost:3000/reviews`,
    ...(params ? [params] : []),
  ] as const;
};

export const getApiReviewsGetCollectionQueryOptions = <
  TData = Awaited<ReturnType<typeof apiReviewsGetCollection>>,
  TError = unknown,
>(
  params?: ApiReviewsGetCollectionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiReviewsGetCollection>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getApiReviewsGetCollectionQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof apiReviewsGetCollection>>
  > = ({ signal }) =>
    apiReviewsGetCollection(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof apiReviewsGetCollection>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ApiReviewsGetCollectionQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiReviewsGetCollection>>
>;
export type ApiReviewsGetCollectionQueryError = unknown;

export function useApiReviewsGetCollection<
  TData = Awaited<ReturnType<typeof apiReviewsGetCollection>>,
  TError = unknown,
>(
  params: undefined | ApiReviewsGetCollectionParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiReviewsGetCollection>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiReviewsGetCollection>>,
          TError,
          Awaited<ReturnType<typeof apiReviewsGetCollection>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useApiReviewsGetCollection<
  TData = Awaited<ReturnType<typeof apiReviewsGetCollection>>,
  TError = unknown,
>(
  params?: ApiReviewsGetCollectionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiReviewsGetCollection>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiReviewsGetCollection>>,
          TError,
          Awaited<ReturnType<typeof apiReviewsGetCollection>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useApiReviewsGetCollection<
  TData = Awaited<ReturnType<typeof apiReviewsGetCollection>>,
  TError = unknown,
>(
  params?: ApiReviewsGetCollectionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiReviewsGetCollection>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Retrieves the collection of Review resources.
 */

export function useApiReviewsGetCollection<
  TData = Awaited<ReturnType<typeof apiReviewsGetCollection>>,
  TError = unknown,
>(
  params?: ApiReviewsGetCollectionParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiReviewsGetCollection>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getApiReviewsGetCollectionQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Creates a Review resource.
 * @summary Creates a Review resource.
 */
export type apiReviewsPostResponse201 = {
  data: ReviewJsonld;
  status: 201;
};

export type apiReviewsPostResponse400ApplicationLdJson = {
  data: ErrorJsonld;
  status: 400;
};

export type apiReviewsPostResponse400ApplicationProblemJson = {
  data: Error;
  status: 400;
};

export type apiReviewsPostResponse422ApplicationLdJson = {
  data: ConstraintViolationJsonldJsonld;
  status: 422;
};

export type apiReviewsPostResponse422ApplicationProblemJson = {
  data: ConstraintViolationJson;
  status: 422;
};

export type apiReviewsPostResponseSuccess = apiReviewsPostResponse201 & {
  headers: Headers;
};
export type apiReviewsPostResponseError = (
  | apiReviewsPostResponse400ApplicationLdJson
  | apiReviewsPostResponse400ApplicationProblemJson
  | apiReviewsPostResponse422ApplicationLdJson
  | apiReviewsPostResponse422ApplicationProblemJson
) & {
  headers: Headers;
};

export type apiReviewsPostResponse =
  | apiReviewsPostResponseSuccess
  | apiReviewsPostResponseError;

export const getApiReviewsPostUrl = () => {
  return `http://localhost:3000/reviews`;
};

export const apiReviewsPost = async (
  reviewJsonld: NonReadonly<ReviewJsonld>,
  options?: RequestInit,
): Promise<apiReviewsPostResponse> => {
  return customFetch<apiReviewsPostResponse>(getApiReviewsPostUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/ld+json", ...options?.headers },
    body: JSON.stringify(reviewJsonld),
  });
};

export const getApiReviewsPostMutationOptions = <
  TError =
    | ErrorJsonld
    | Error
    | ConstraintViolationJsonldJsonld
    | ConstraintViolationJson,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiReviewsPost>>,
    TError,
    { data: NonReadonly<ReviewJsonld> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiReviewsPost>>,
  TError,
  { data: NonReadonly<ReviewJsonld> },
  TContext
> => {
  const mutationKey = ["apiReviewsPost"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiReviewsPost>>,
    { data: NonReadonly<ReviewJsonld> }
  > = (props) => {
    const { data } = props ?? {};

    return apiReviewsPost(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApiReviewsPostMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiReviewsPost>>
>;
export type ApiReviewsPostMutationBody = NonReadonly<ReviewJsonld>;
export type ApiReviewsPostMutationError =
  | ErrorJsonld
  | Error
  | ConstraintViolationJsonldJsonld
  | ConstraintViolationJson;

/**
 * @summary Creates a Review resource.
 */
export const useApiReviewsPost = <
  TError =
    | ErrorJsonld
    | Error
    | ConstraintViolationJsonldJsonld
    | ConstraintViolationJson,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiReviewsPost>>,
      TError,
      { data: NonReadonly<ReviewJsonld> },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof apiReviewsPost>>,
  TError,
  { data: NonReadonly<ReviewJsonld> },
  TContext
> => {
  const mutationOptions = getApiReviewsPostMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Retrieves a Review resource.
 * @summary Retrieves a Review resource.
 */
export type apiReviewsIdGetResponse200 = {
  data: ReviewJsonld;
  status: 200;
};

export type apiReviewsIdGetResponse404ApplicationLdJson = {
  data: ErrorJsonld;
  status: 404;
};

export type apiReviewsIdGetResponse404ApplicationProblemJson = {
  data: Error;
  status: 404;
};

export type apiReviewsIdGetResponseSuccess = apiReviewsIdGetResponse200 & {
  headers: Headers;
};
export type apiReviewsIdGetResponseError = (
  | apiReviewsIdGetResponse404ApplicationLdJson
  | apiReviewsIdGetResponse404ApplicationProblemJson
) & {
  headers: Headers;
};

export type apiReviewsIdGetResponse =
  | apiReviewsIdGetResponseSuccess
  | apiReviewsIdGetResponseError;

export const getApiReviewsIdGetUrl = (id: string) => {
  return `http://localhost:3000/reviews/${id}`;
};

export const apiReviewsIdGet = async (
  id: string,
  options?: RequestInit,
): Promise<apiReviewsIdGetResponse> => {
  return customFetch<apiReviewsIdGetResponse>(getApiReviewsIdGetUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getApiReviewsIdGetQueryKey = (id?: string) => {
  return [`http://localhost:3000/reviews/${id}`] as const;
};

export const getApiReviewsIdGetQueryOptions = <
  TData = Awaited<ReturnType<typeof apiReviewsIdGet>>,
  TError = ErrorJsonld | Error,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiReviewsIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getApiReviewsIdGetQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof apiReviewsIdGet>>> = ({
    signal,
  }) => apiReviewsIdGet(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof apiReviewsIdGet>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ApiReviewsIdGetQueryResult = NonNullable<
  Awaited<ReturnType<typeof apiReviewsIdGet>>
>;
export type ApiReviewsIdGetQueryError = ErrorJsonld | Error;

export function useApiReviewsIdGet<
  TData = Awaited<ReturnType<typeof apiReviewsIdGet>>,
  TError = ErrorJsonld | Error,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiReviewsIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiReviewsIdGet>>,
          TError,
          Awaited<ReturnType<typeof apiReviewsIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useApiReviewsIdGet<
  TData = Awaited<ReturnType<typeof apiReviewsIdGet>>,
  TError = ErrorJsonld | Error,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiReviewsIdGet>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof apiReviewsIdGet>>,
          TError,
          Awaited<ReturnType<typeof apiReviewsIdGet>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useApiReviewsIdGet<
  TData = Awaited<ReturnType<typeof apiReviewsIdGet>>,
  TError = ErrorJsonld | Error,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiReviewsIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Retrieves a Review resource.
 */

export function useApiReviewsIdGet<
  TData = Awaited<ReturnType<typeof apiReviewsIdGet>>,
  TError = ErrorJsonld | Error,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof apiReviewsIdGet>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getApiReviewsIdGetQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Removes the Review resource.
 * @summary Removes the Review resource.
 */
export type apiReviewsIdDeleteResponse204 = {
  data: void;
  status: 204;
};

export type apiReviewsIdDeleteResponse404ApplicationLdJson = {
  data: ErrorJsonld;
  status: 404;
};

export type apiReviewsIdDeleteResponse404ApplicationProblemJson = {
  data: Error;
  status: 404;
};

export type apiReviewsIdDeleteResponseSuccess =
  apiReviewsIdDeleteResponse204 & {
    headers: Headers;
  };
export type apiReviewsIdDeleteResponseError = (
  | apiReviewsIdDeleteResponse404ApplicationLdJson
  | apiReviewsIdDeleteResponse404ApplicationProblemJson
) & {
  headers: Headers;
};

export type apiReviewsIdDeleteResponse =
  | apiReviewsIdDeleteResponseSuccess
  | apiReviewsIdDeleteResponseError;

export const getApiReviewsIdDeleteUrl = (id: string) => {
  return `http://localhost:3000/reviews/${id}`;
};

export const apiReviewsIdDelete = async (
  id: string,
  options?: RequestInit,
): Promise<apiReviewsIdDeleteResponse> => {
  return customFetch<apiReviewsIdDeleteResponse>(getApiReviewsIdDeleteUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getApiReviewsIdDeleteMutationOptions = <
  TError = ErrorJsonld | Error,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiReviewsIdDelete>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiReviewsIdDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["apiReviewsIdDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiReviewsIdDelete>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return apiReviewsIdDelete(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApiReviewsIdDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiReviewsIdDelete>>
>;

export type ApiReviewsIdDeleteMutationError = ErrorJsonld | Error;

/**
 * @summary Removes the Review resource.
 */
export const useApiReviewsIdDelete = <
  TError = ErrorJsonld | Error,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiReviewsIdDelete>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof apiReviewsIdDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationOptions = getApiReviewsIdDeleteMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Updates the Review resource.
 * @summary Updates the Review resource.
 */
export type apiReviewsIdPatchResponse200 = {
  data: ReviewJsonld;
  status: 200;
};

export type apiReviewsIdPatchResponse400ApplicationLdJson = {
  data: ErrorJsonld;
  status: 400;
};

export type apiReviewsIdPatchResponse400ApplicationProblemJson = {
  data: Error;
  status: 400;
};

export type apiReviewsIdPatchResponse404ApplicationLdJson = {
  data: ErrorJsonld;
  status: 404;
};

export type apiReviewsIdPatchResponse404ApplicationProblemJson = {
  data: Error;
  status: 404;
};

export type apiReviewsIdPatchResponse422ApplicationLdJson = {
  data: ConstraintViolationJsonldJsonld;
  status: 422;
};

export type apiReviewsIdPatchResponse422ApplicationProblemJson = {
  data: ConstraintViolationJson;
  status: 422;
};

export type apiReviewsIdPatchResponseSuccess = apiReviewsIdPatchResponse200 & {
  headers: Headers;
};
export type apiReviewsIdPatchResponseError = (
  | apiReviewsIdPatchResponse400ApplicationLdJson
  | apiReviewsIdPatchResponse400ApplicationProblemJson
  | apiReviewsIdPatchResponse404ApplicationLdJson
  | apiReviewsIdPatchResponse404ApplicationProblemJson
  | apiReviewsIdPatchResponse422ApplicationLdJson
  | apiReviewsIdPatchResponse422ApplicationProblemJson
) & {
  headers: Headers;
};

export type apiReviewsIdPatchResponse =
  | apiReviewsIdPatchResponseSuccess
  | apiReviewsIdPatchResponseError;

export const getApiReviewsIdPatchUrl = (id: string) => {
  return `http://localhost:3000/reviews/${id}`;
};

export const apiReviewsIdPatch = async (
  id: string,
  review: NonReadonly<Review>,
  options?: RequestInit,
): Promise<apiReviewsIdPatchResponse> => {
  return customFetch<apiReviewsIdPatchResponse>(getApiReviewsIdPatchUrl(id), {
    ...options,
    method: "PATCH",
    headers: {
      "Content-Type": "application/merge-patch+json",
      ...options?.headers,
    },
    body: JSON.stringify(review),
  });
};

export const getApiReviewsIdPatchMutationOptions = <
  TError =
    | ErrorJsonld
    | Error
    | ConstraintViolationJsonldJsonld
    | ConstraintViolationJson,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof apiReviewsIdPatch>>,
    TError,
    { id: string; data: NonReadonly<Review> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof apiReviewsIdPatch>>,
  TError,
  { id: string; data: NonReadonly<Review> },
  TContext
> => {
  const mutationKey = ["apiReviewsIdPatch"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof apiReviewsIdPatch>>,
    { id: string; data: NonReadonly<Review> }
  > = (props) => {
    const { id, data } = props ?? {};

    return apiReviewsIdPatch(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ApiReviewsIdPatchMutationResult = NonNullable<
  Awaited<ReturnType<typeof apiReviewsIdPatch>>
>;
export type ApiReviewsIdPatchMutationBody = NonReadonly<Review>;
export type ApiReviewsIdPatchMutationError =
  | ErrorJsonld
  | Error
  | ConstraintViolationJsonldJsonld
  | ConstraintViolationJson;

/**
 * @summary Updates the Review resource.
 */
export const useApiReviewsIdPatch = <
  TError =
    | ErrorJsonld
    | Error
    | ConstraintViolationJsonldJsonld
    | ConstraintViolationJson,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof apiReviewsIdPatch>>,
      TError,
      { id: string; data: NonReadonly<Review> },
      TContext
    >;
    request?: SecondParameter<typeof customFetch>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof apiReviewsIdPatch>>,
  TError,
  { id: string; data: NonReadonly<Review> },
  TContext
> => {
  const mutationOptions = getApiReviewsIdPatchMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
