/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { BookJsonld } from "./bookJsonld";
import type { ApiBooksGetCollection200View } from "./apiBooksGetCollection200View";
import type { ApiBooksGetCollection200Search } from "./apiBooksGetCollection200Search";

export type ApiBooksGetCollection200 = {
  member: BookJsonld[];
  /** @minimum 0 */
  totalItems?: number;
  view?: ApiBooksGetCollection200View;
  search?: ApiBooksGetCollection200Search;
};
