/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ApiBooksGetCollection200SearchMappingItem } from "./apiBooksGetCollection200SearchMappingItem";

export type ApiBooksGetCollection200Search = {
  "@type"?: string;
  template?: string;
  variableRepresentation?: string;
  mapping?: ApiBooksGetCollection200SearchMappingItem[];
};
