/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ApiBooksGetCollection200SearchMappingItemProperty } from "./apiBooksGetCollection200SearchMappingItemProperty";

export type ApiBooksGetCollection200SearchMappingItem = {
  "@type"?: string;
  variable?: string;
  property?: ApiBooksGetCollection200SearchMappingItemProperty;
  required?: boolean;
};
