/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ApiReviewsGetCollection200SearchMappingItemProperty } from "./apiReviewsGetCollection200SearchMappingItemProperty";

export type ApiReviewsGetCollection200SearchMappingItem = {
  "@type"?: string;
  variable?: string;
  property?: ApiReviewsGetCollection200SearchMappingItemProperty;
  required?: boolean;
};
