/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ApiReviewsGetCollection200SearchMappingItem } from "./apiReviewsGetCollection200SearchMappingItem";

export type ApiReviewsGetCollection200Search = {
  "@type"?: string;
  template?: string;
  variableRepresentation?: string;
  mapping?: ApiReviewsGetCollection200SearchMappingItem[];
};
