/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ReviewJsonld } from "./reviewJsonld";
import type { ApiReviewsGetCollection200View } from "./apiReviewsGetCollection200View";
import type { ApiReviewsGetCollection200Search } from "./apiReviewsGetCollection200Search";

export type ApiReviewsGetCollection200 = {
  member: ReviewJsonld[];
  /** @minimum 0 */
  totalItems?: number;
  view?: ApiReviewsGetCollection200View;
  search?: ApiReviewsGetCollection200Search;
};
