/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { BookRating } from "./bookRating";
import type { BookBody } from "./bookBody";

export interface Book {
  readonly id?: number;
  rating?: BookRating;
  body?: BookBody;
  author?: string;
  reviews?: string[];
}
