/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ConstraintViolationJsonldJsonldContext } from "./constraintViolationJsonldJsonldContext";
import type { ConstraintViolationJsonldJsonldViolationsItem } from "./constraintViolationJsonldJsonldViolationsItem";
import type { ConstraintViolationJsonldJsonldTitle } from "./constraintViolationJsonldJsonldTitle";
import type { ConstraintViolationJsonldJsonldInstance } from "./constraintViolationJsonldJsonldInstance";

/**
 * Unprocessable entity
 */
export interface ConstraintViolationJsonldJsonld {
  readonly "@context"?: ConstraintViolationJsonldJsonldContext;
  readonly "@id"?: string;
  readonly "@type"?: string;
  status?: number;
  violations?: ConstraintViolationJsonldJsonldViolationsItem[];
  readonly detail?: string;
  readonly description?: string;
  readonly type?: string;
  readonly title?: ConstraintViolationJsonldJsonldTitle;
  readonly instance?: ConstraintViolationJsonldJsonldInstance;
}
