/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */

export type ConstraintViolationJsonViolationsItem = {
  /** The property path of the violation */
  propertyPath?: string;
  /** The message associated with the violation */
  message?: string;
};
