/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */

export type ErrorJsonldContextOneOfHydra =
  (typeof ErrorJsonldContextOneOfHydra)[keyof typeof ErrorJsonldContextOneOfHydra];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ErrorJsonldContextOneOfHydra = {
  "http://wwww3org/ns/hydra/core#": "http://www.w3.org/ns/hydra/core#",
} as const;
