/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */

/**
 * A human-readable explanation specific to this occurrence of the problem.
 */
export type ErrorDetail = string | null;
