/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */

/**
 * A URI reference that identifies the specific occurrence of the problem. It may or may not yield further information if dereferenced.
 */
export type ErrorInstance = string | null;
