/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ErrorJsonldContextOneOfHydra } from "./errorJsonldContextOneOfHydra";

export type ErrorJsonldContextOneOf = {
  "@vocab": string;
  hydra: ErrorJsonldContextOneOfHydra;
  [key: string]: unknown;
};
