/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */

/**
 * A short, human-readable summary of the problem.
 */
export type ErrorTitle = string | null;
