/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */

export * from "./apiBooksGetCollection200";
export * from "./apiBooksGetCollection200Search";
export * from "./apiBooksGetCollection200SearchMappingItem";
export * from "./apiBooksGetCollection200SearchMappingItemProperty";
export * from "./apiBooksGetCollection200View";
export * from "./apiBooksGetCollectionParams";
export * from "./apiReviewsGetCollection200";
export * from "./apiReviewsGetCollection200Search";
export * from "./apiReviewsGetCollection200SearchMappingItem";
export * from "./apiReviewsGetCollection200SearchMappingItemProperty";
export * from "./apiReviewsGetCollection200View";
export * from "./apiReviewsGetCollectionParams";
export * from "./book";
export * from "./bookBody";
export * from "./bookJsonld";
export * from "./bookJsonldBody";
export * from "./bookJsonldContext";
export * from "./bookJsonldContextOneOf";
export * from "./bookJsonldContextOneOfHydra";
export * from "./bookJsonldRating";
export * from "./bookRating";
export * from "./constraintViolationJson";
export * from "./constraintViolationJsonInstance";
export * from "./constraintViolationJsonTitle";
export * from "./constraintViolationJsonViolationsItem";
export * from "./constraintViolationJsonldJsonld";
export * from "./constraintViolationJsonldJsonldContext";
export * from "./constraintViolationJsonldJsonldContextOneOf";
export * from "./constraintViolationJsonldJsonldContextOneOfHydra";
export * from "./constraintViolationJsonldJsonldInstance";
export * from "./constraintViolationJsonldJsonldTitle";
export * from "./constraintViolationJsonldJsonldViolationsItem";
export * from "./error";
export * from "./errorDetail";
export * from "./errorInstance";
export * from "./errorJsonld";
export * from "./errorJsonldContext";
export * from "./errorJsonldContextOneOf";
export * from "./errorJsonldContextOneOfHydra";
export * from "./errorJsonldDescription";
export * from "./errorJsonldDetail";
export * from "./errorJsonldInstance";
export * from "./errorJsonldTitle";
export * from "./errorTitle";
export * from "./review";
export * from "./reviewJsonld";
export * from "./reviewJsonldContext";
export * from "./reviewJsonldContextOneOf";
export * from "./reviewJsonldContextOneOfHydra";
