/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ReviewJsonldContextOneOfHydra } from "./reviewJsonldContextOneOfHydra";

export type ReviewJsonldContextOneOf = {
  "@vocab": string;
  hydra: ReviewJsonldContextOneOfHydra;
  [key: string]: unknown;
};
