/**
 * Generated by orval v8.0.0-rc.0 🍺
 * Do not edit manually.
 * Hello API Platform
 * OpenAPI spec version: 1.0.0
 */
import type { ReviewJsonldContext } from "./reviewJsonldContext";

export interface ReviewJsonld {
  readonly "@context"?: ReviewJsonldContext;
  readonly "@id"?: string;
  readonly "@type"?: string;
  readonly id?: number;
  author?: string;
  book?: string;
  body?: string;
}
